# Generated by Django 5.2.15 on 2026-07-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('core', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '검토중'), ('ACCEPTED', '수락'), ('REJECTED', '거절')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='worker.workerprofile')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='ApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.application')),
            ],
            options={
                'db_table': 'application_file',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('WARMUP', '워밍업'), ('REAL', '실무')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('work_style', models.CharField(choices=[('REMOTE', '100% 재택'), ('ONSITE_WEEKLY_1', '주 1회 출근'), ('ONSITE_WEEKLY_3', '주 3회 이상 출근'), ('ONSITE_DAILY', '매일 출근')], max_length=20)),
                ('weekly_hours', models.CharField(choices=[('UNDER_15', '주 15시간 미만'), ('FIFTEEN_TO_25', '주 15시간~25시간'), ('OVER_25', '주 25시간 이상')], max_length=20)),
                ('compensation_amount', models.IntegerField()),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('recruitment_count', models.IntegerField()),
                ('career_years', models.CharField(choices=[('ONE_TO_THREE', '1~3년'), ('THREE_TO_FIVE', '3~5년'), ('FIVE_TO_SEVEN', '5~7년'), ('OVER_SEVEN', '7년 이상')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', '모집중'), ('SELECTING', '선발중'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료')], default='OPEN', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company.companyprofile')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.jobcategory')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Returnship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', '응답대기'), ('ACCEPTED', '수락'), ('REJECTED', '거절')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='returnship', to='projects.application')),
            ],
            options={
                'db_table': 'returnship_offer',
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('project', 'worker_profile')},
        ),
        migrations.CreateModel(
            name='ProjectCoreTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_times', to='projects.project')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_core_times', to='core.timeslot')),
            ],
            options={
                'db_table': 'project_core_time',
                'unique_together': {('project', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='ProjectHiddenAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_hidden_abilities', to='core.hiddenability')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_abilities', to='projects.project')),
            ],
            options={
                'db_table': 'project_hidden_ability',
                'unique_together': {('project', 'hidden_ability')},
            },
        ),
        migrations.CreateModel(
            name='ProjectPreferredScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_type', models.CharField(choices=[('SHORT', '1~2주 단기'), ('LONG', '1개월 이상 중기'), ('REGULAR_TRANSITION', '정규직 전환 전제(리턴십)')], max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_scales', to='projects.project')),
            ],
            options={
                'db_table': 'project_preferred_scale',
                'unique_together': {('project', 'scale_type')},
            },
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('NORMAL', '필수'), ('PREFERRED', '우대')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='projects.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='core.skill')),
            ],
            options={
                'db_table': 'project_skill',
                'unique_together': {('project', 'skill')},
            },
        ),
    ]
