# Generated by Django 5.2.15 on 2026-07-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfile',
            name='file_url',
        ),
        migrations.AddField(
            model_name='applicationfile',
            name='file',
            field=models.FileField(default='', upload_to='applications/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
