# Generated by Django 5.2.15 on 2026-07-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='LLM 분류 프롬프트에 그대로 넣을 판단 기준 설명')),
            ],
            options={
                'db_table': 'hidden_ability',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'job_category',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'time_slot',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='core.jobcategory')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='core.skill')),
            ],
            options={
                'db_table': 'job_skill',
            },
        ),
        migrations.CreateModel(
            name='JobHiddenAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_hidden_abilities', to='core.hiddenability')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_hidden_abilities', to='core.jobcategory')),
            ],
            options={
                'db_table': 'job_hidden_ability',
                'unique_together': {('job_category', 'hidden_ability')},
            },
        ),
    ]
