# Generated by Django 5.2.15 on 2026-07-09 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_years', models.CharField(choices=[('ONE_TO_THREE', '1~3년'), ('THREE_TO_FIVE', '3~5년'), ('FIVE_TO_SEVEN', '5~7년'), ('OVER_SEVEN', '7년 이상')], help_text='온보딩2 연차 선택', max_length=20)),
                ('achievement_keywords', models.CharField(blank=True, help_text='온보딩2', max_length=500, null=True)),
                ('weekly_hours', models.CharField(choices=[('UNDER_15', '주 15시간 미만'), ('FIFTEEN_TO_25', '주 15시간~25시간'), ('OVER_25', '주 25시간 이상')], help_text='온보딩3', max_length=20)),
                ('preferred_work_style', models.CharField(choices=[('REMOTE', '100% 재택'), ('ONSITE_WEEKLY_1', '주 1회 출근'), ('ONSITE_WEEKLY_3', '주 3회 이상 출근'), ('ONSITE_DAILY', '매일 출근')], help_text='온보딩3', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_type', models.CharField(blank=True, choices=[('WARMUP', '워밍업 프로젝트'), ('REAL', '실무 프로젝트')], help_text="온보딩4: 'WARMUP', 'REAL'", max_length=50, null=True)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profiles', to='core.jobcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worker_profile',
            },
        ),
        migrations.CreateModel(
            name='WorkerHiddenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_text', models.CharField(max_length=300)),
                ('hidden_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_activities', to='core.hiddenability')),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_activities', to='worker.workerprofile')),
            ],
            options={
                'db_table': 'worker_hidden_activity',
            },
        ),
        migrations.CreateModel(
            name='WorkerPreferredScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_type', models.CharField(choices=[('SHORT', '1~2주 단기'), ('LONG', '1개월 이상 중기'), ('REGULAR_TRANSITION', '정규직 전환 전제(리턴십)')], max_length=30)),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_scales', to='worker.workerprofile')),
            ],
            options={
                'db_table': 'worker_preferred_scale',
                'unique_together': {('worker_profile', 'scale_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkerCoreTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_core_times', to='core.timeslot')),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_times', to='worker.workerprofile')),
            ],
            options={
                'db_table': 'worker_core_time',
                'unique_together': {('worker_profile', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='WorkerConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_type', models.CharField(choices=[('DIGITAL_SKILL', '최신 트렌드·지식 부족'), ('COMMUNICATION', '커뮤니케이션 자신감 저하'), ('PHYSICAL_BURDEN', '체력적인 부담'), ('CHILDCARE', '가사 병행의 어려움'), ('CAREER_GAP_ANXIETY', '경력 공백에 대한 시선')], max_length=30)),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='worker.workerprofile')),
            ],
            options={
                'db_table': 'worker_concern',
                'unique_together': {('worker_profile', 'concern_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_skills', to='core.skill')),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_skills', to='worker.workerprofile')),
            ],
            options={
                'db_table': 'worker_skill',
                'unique_together': {('worker_profile', 'skill')},
            },
        ),
    ]
